name: Test Validation Action
on:
  push:
    branches:
      - 'dev'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2
    - name: run custom docker testLog
      id: testAction
      uses: ./
      with:
        run-script-python3: 'test/version.py'
    - name: Get the output result
      run: echo "The result is ${{ steps.testAction.outputs.result-python3 }}"
